apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cerber-availability-api.fullname" . }}
  labels:
    {{- include "cerber-availability-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cerber-availability-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cerber-availability-api.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "cerber-availability-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: AVAILABILITYAPI_Docker__BasePath
            value: /gateway/availability/
          - name: Token__Key
            valueFrom:
              secretKeyRef:
                name: token
                key: key
          - name: ConnectionStrings__Cerber
            valueFrom:
              secretKeyRef:
                name: connection-strings
                key: cerber-availability
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
