apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - name: tcp
      protocol: TCP
      port: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cerber-managed-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: default
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        imagePullPolicy: Always
        resources: {}
        volumeMounts:
        - mountPath: "/mnt/azure"
          name: volume
      restartPolicy: Always
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: cerber-managed-disk