apiVersion: batch/v1
kind: Job
metadata:
  name: cerber-availability-worker
spec:
  template:
    spec:
      imagePullSecrets:
      - name: azurecr
      containers:
      - name: cerber-availability-worker
        image: ppasekdevcontainers.azurecr.io/cerber-availability-worker
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ConnectionStrings__Cerber
          valueFrom:
            secretKeyRef:
              name: connection-strings
              key: cerber-availability
      restartPolicy: OnFailure
  backoffLimit: 4